gazebo_ros_control/pid_gains:

  # joint1: {p: 5000.0, i: 5000, d: 85}
  # joint2: {p: 10000.0, i: 10000, d: 100}
  # joint3: {p: 10000.0, i: 10000, d: 100}
  # joint4: {p: 5000.0, i: 5000, d: 85}
  # joint5: {p: 6000.0, i: 6000, d: 85}
  # joint6: {p: 5000.0, i: 5000, d: 85}

  # front_left_wheel:  {p: 500.0, i: 0.0, d: 1.0}
  # front_right_wheel: {p: 500.0, i: 0.0, d: 1.0}
  # rear_left_wheel:   {p: 500.0, i: 0.0, d: 1.0}
  # rear_right_wheel:  {p: 500.0, i: 0.0, d: 1.0}
  robotiq_85_left_knuckle_joint: {p: 40, d: 0, i: 0}
        